### ISSUE TITLE
Configured lookup table http-status-codes-lookup doesn't exist.

### ISSUE THREAD

**Issue by Zvezdelin** [xkill/graylog_4.1_ssh#1]
Hello! Thanks for the ssh content pack!
After installation in dashboard SSH, following error message appears:
***
_(Widget) Accepted logins summary

While retrieving data for this widget, the following error(s) occurred:
Configured lookup table <http-status-codes-lookup> doesn't exist._
***
Where can I get this lookup table?

Best!

**Comment by ctobada** [comment]
Did you find a solution ?

**Comment by SystronX** [comment]
Hello, I have the same problem.

While retrieving data for this widget, the following error(s) occurred:
Configured lookup table <http-status-codes-lookup> doesn't exist.

**Comment by Mickatronic** [comment]
Same :(

**Comment by xkill** [comment]
Removed the lookup tables. Can you check that it works fine?
